name: ci
on:
  pull_request:

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: install dependencies
        run: npm ci

      - name: run debug script
        run: ./debug-check.sh

      - name: check formatting on diff
        shell: bash
        run: |
          set -euo pipefail
          BASE_REF="${{ github.event_name == 'pull_request' && github.base_ref || 'main' }}"
          git fetch origin "$BASE_REF"
          FILES=$(git diff --name-only "origin/$BASE_REF...HEAD" | grep -E '\.(js|ts|jsx|tsx|ejs|json|css|scss|md|html|ya?ml)$' || true)
          if [[ -n "$FILES" ]]; then
            echo "Checking formatting for:"
            echo "$FILES"
            if echo "$FILES" | xargs npx prettier --check; then
              echo "✅ All files are properly formatted"
            else
              echo "❌ Some files need formatting"
              exit 1
            fi
          else
            echo "No files need formatting"
          fi
